src/Entity/ProductStock.php
<?php

namespace App\Entity;

use App\Repository\ProductStockRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductStockRepository::class)
 */
class ProductStock
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $expiration_date;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="product_stock")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity=ProductOwner::class, inversedBy="productStocks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product_owner;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExpirationDate(): ?\DateTimeInterface
    {
        return $this->expiration_date;
    }

    public function setExpirationDate(?\DateTimeInterface $expiration_date): self
    {
        $this->expiration_date = $expiration_date;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getProductOwner(): ?ProductOwner
    {
        return $this->product_owner;
    }

    public function setProductOwner(?ProductOwner $product_owner): self
    {
        $this->product_owner = $product_owner;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

src/Form/ProductStockType.php
<?php

namespace App\Form;

use App\Entity\ProductStock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Product;
use App\Entity\ProductOwner;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProductStockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('expiration_date')
            ->add('quantity')
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name',
            ])
            ->add('product_owner', EntityType::class, [
                'class' => ProductOwner::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ProductStock::class,
        ]);
    }
}

src/Controller/ProductStockController.php
<?php

namespace App\Controller;

use App\Entity\ProductStock;
use App\Form\ProductStockType;
use App\Repository\ProductStockRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/stock")
 */
class ProductStockController extends AbstractController
{
    /**
     * @Route("/", name="product_stock_index", methods={"GET"})
     */
    public function index(ProductStockRepository $productStockRepository): Response
    {
        return $this->render('product_stock/index.html.twig', [
            'product_stocks' => $productStockRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="product_stock_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $productStock = new ProductStock();
        $form = $this->createForm(ProductStockType::class, $productStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($productStock);
            $entityManager->flush();

            return $this->redirectToRoute('product_stock_index');
        }

        return $this->render('product_stock/new.html.twig', [
            'product_stock' => $productStock,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_stock_show", methods={"GET"})
     */
    public function show(ProductStock $productStock): Response
    {
        return $this->render('product_stock/show.html.twig', [
            'product_stock' => $productStock,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="product_stock_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ProductStock $productStock): Response
    {
        $form = $this->createForm(ProductStockType::class, $productStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_stock_index');
        }

        return $this->render('product_stock/edit.html.twig', [
            'product_stock' => $productStock,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_stock_delete", methods={"DELETE"})
     */
    public function delete(Request $request, ProductStock $productStock): Response
    {
        if ($this->isCsrfTokenValid('delete'.$productStock->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($productStock);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_stock_index');
    }
}

templates/product_stock/_delete_form.html.twig
<form method="post" action="{{ path('product_stock_delete', {'id': product_stock.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product_stock.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product_stock/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product_stock/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProductStock{% endblock %}

{% block body %}
    <h1>Edit ProductStock</h1>

    {{ include('product_stock/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_stock_index') }}">back to list</a>

    {{ include('product_stock/_delete_form.html.twig') }}
{% endblock %}

templates/product_stock/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductStock index{% endblock %}

{% block body %}
    <h1>ProductStock index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Expiration_date</th>
                <th>Quantity</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product_stock in product_stocks %}
            <tr>
                <td>{{ product_stock.id }}</td>
                <td>{{ product_stock.expirationDate ? product_stock.expirationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ product_stock.quantity }}</td>
                <td>
                    <a href="{{ path('product_stock_show', {'id': product_stock.id}) }}">show</a>
                    <a href="{{ path('product_stock_edit', {'id': product_stock.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('product_stock_new') }}">Create new</a>
{% endblock %}

templates/product_stock/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProductStock{% endblock %}

{% block body %}
    <h1>Create new ProductStock</h1>

    {{ include('product_stock/_form.html.twig') }}

    <a href="{{ path('product_stock_index') }}">back to list</a>
{% endblock %}

templates/product_stock/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductStock{% endblock %}

{% block body %}
    <h1>ProductStock</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product_stock.id }}</td>
            </tr>
            <tr>
                <th>Expiration_date</th>
                <td>{{ product_stock.expirationDate ? product_stock.expirationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ product_stock.quantity }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('product_stock_index') }}">back to list</a>

    <a href="{{ path('product_stock_edit', {'id': product_stock.id}) }}">edit</a>

    {{ include('product_stock/_delete_form.html.twig') }}
{% endblock %}